
WebDKP_Options = {
	["SelectedTableId"] = 1,
	["AutofillEnabled"] = 1,
	["MiniMapButtonAngle"] = -1.690968964428301,
	["AutofillThreshold"] = 2,
	["AutoAwardEnabled"] = 1,
}
WebDKP_Log = {
	["Ready and signed up 2017-06-30 18:55:21"] = {
		["awarded"] = {
			["Gallatrix"] = {
				["name"] = "Gallatrix",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Molteny"] = {
				["name"] = "Molteny",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Phoee"] = {
				["name"] = "Phoee",
				["class"] = "Druid",
				["guild"] = "SIN",
			},
			["Beelzemut"] = {
				["name"] = "Beelzemut",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Rozaliina"] = {
				["name"] = "Rozaliina",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Kontaz"] = {
				["name"] = "Kontaz",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Valri"] = {
				["name"] = "Valri",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Eddness"] = {
				["name"] = "Eddness",
				["class"] = "Shaman",
				["guild"] = "SIN",
			},
			["Krocan"] = {
				["name"] = "Krocan",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Vay"] = {
				["name"] = "Vay",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Menergy"] = {
				["class"] = "Warrior",
				["name"] = "Menergy",
			},
			["Frostmist"] = {
				["name"] = "Frostmist",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Nagreil"] = {
				["name"] = "Nagreil",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Lemonlock"] = {
				["name"] = "Lemonlock",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Watson"] = {
				["name"] = "Watson",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Freezma"] = {
				["name"] = "Freezma",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Stabbeh"] = {
				["name"] = "Stabbeh",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Hurksmash"] = {
				["name"] = "Hurksmash",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Lustbliss"] = {
				["name"] = "Lustbliss",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Wiseguyhuh"] = {
				["name"] = "Wiseguyhuh",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Celembris"] = {
				["name"] = "Celembris",
				["class"] = "Shaman",
				["guild"] = "SIN",
			},
			["Haywanat"] = {
				["name"] = "Haywanat",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Elalabama"] = {
				["name"] = "Elalabama",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Sustainlife"] = {
				["name"] = "Sustainlife",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Nozx"] = {
				["name"] = "Nozx",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Actar"] = {
				["name"] = "Actar",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Bruteforge"] = {
				["name"] = "Bruteforge",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
		},
		["zone"] = "Badlands",
		["date"] = "2017-06-30 18:55:21",
		["reason"] = "Ready and signed up",
		["foritem"] = "false",
		["points"] = 5,
		["awardedby"] = "Actar",
		["tableid"] = 1,
	},
	["Version"] = 2,
	["The Molten Core: Shazzrah 2017-06-30 20:24:16"] = {
		["awarded"] = {
			["Nozx"] = {
				["name"] = "Nozx",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Molteny"] = {
				["name"] = "Molteny",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Phoee"] = {
				["name"] = "Phoee",
				["class"] = "Druid",
				["guild"] = "SIN",
			},
			["Bananular"] = {
				["name"] = "Bananular",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Actar"] = {
				["name"] = "Actar",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Menergy"] = {
				["name"] = "Menergy",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Nagreil"] = {
				["name"] = "Nagreil",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Watson"] = {
				["name"] = "Watson",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Wiseguyhuh"] = {
				["name"] = "Wiseguyhuh",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Elalabama"] = {
				["name"] = "Elalabama",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Gallatrix"] = {
				["name"] = "Gallatrix",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Lemonlock"] = {
				["name"] = "Lemonlock",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Hezrul"] = {
				["name"] = "Hezrul",
				["class"] = "Hunter",
				["guild"] = "DARK TIDE",
			},
			["Beelzemut"] = {
				["name"] = "Beelzemut",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Mada"] = {
				["name"] = "Mada",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Kontaz"] = {
				["name"] = "Kontaz",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Valri"] = {
				["name"] = "Valri",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Eddness"] = {
				["name"] = "Eddness",
				["class"] = "Shaman",
				["guild"] = "SIN",
			},
			["Altzheimer"] = {
				["name"] = "Altzheimer",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Unwanting"] = {
				["name"] = "Unwanting",
				["class"] = "Shaman",
				["guild"] = "High Tide",
			},
			["Frostmist"] = {
				["name"] = "Frostmist",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Krocan"] = {
				["name"] = "Krocan",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Dandruk"] = {
				["name"] = "Dandruk",
				["class"] = "Hunter",
				["guild"] = "The Dark Brotherhood",
			},
			["Sgy"] = {
				["name"] = "Sgy",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Freezma"] = {
				["name"] = "Freezma",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Stabbeh"] = {
				["name"] = "Stabbeh",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Hurksmash"] = {
				["name"] = "Hurksmash",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Lustbliss"] = {
				["name"] = "Lustbliss",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Corrax"] = {
				["name"] = "Corrax",
				["class"] = "Shaman",
				["guild"] = "SIN",
			},
			["Rozaliina"] = {
				["name"] = "Rozaliina",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Chorum"] = {
				["name"] = "Chorum",
				["class"] = "Priest",
				["guild"] = "Cult",
			},
			["Haywanat"] = {
				["name"] = "Haywanat",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Sustainlife"] = {
				["name"] = "Sustainlife",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Vay"] = {
				["name"] = "Vay",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Celembris"] = {
				["name"] = "Celembris",
				["class"] = "Shaman",
				["guild"] = "SIN",
			},
			["Bruteforge"] = {
				["name"] = "Bruteforge",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
		},
		["zone"] = "The Molten Core",
		["date"] = "2017-06-30 20:24:16",
		["reason"] = "The Molten Core: Shazzrah",
		["foritem"] = "false",
		["points"] = 5,
		["awardedby"] = "Actar",
		["tableid"] = 1,
	},
	["The Molten Core: Golemagg the Incinerator 2017-06-30 21:20:11"] = {
		["awarded"] = {
			["Nozx"] = {
				["name"] = "Nozx",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Molteny"] = {
				["name"] = "Molteny",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Phoee"] = {
				["name"] = "Phoee",
				["class"] = "Druid",
				["guild"] = "SIN",
			},
			["Bananular"] = {
				["name"] = "Bananular",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Actar"] = {
				["name"] = "Actar",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Menergy"] = {
				["name"] = "Menergy",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Nagreil"] = {
				["name"] = "Nagreil",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Watson"] = {
				["name"] = "Watson",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Wiseguyhuh"] = {
				["name"] = "Wiseguyhuh",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Elalabama"] = {
				["name"] = "Elalabama",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Gallatrix"] = {
				["name"] = "Gallatrix",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Hezrul"] = {
				["name"] = "Hezrul",
				["class"] = "Hunter",
				["guild"] = "DARK TIDE",
			},
			["Beelzemut"] = {
				["name"] = "Beelzemut",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Mada"] = {
				["name"] = "Mada",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Kontaz"] = {
				["name"] = "Kontaz",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Valri"] = {
				["name"] = "Valri",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Eddness"] = {
				["name"] = "Eddness",
				["class"] = "Shaman",
				["guild"] = "SIN",
			},
			["Altzheimer"] = {
				["name"] = "Altzheimer",
				["class"] = "Warlock",
				["guild"] = "SIN",
			},
			["Unwanting"] = {
				["name"] = "Unwanting",
				["class"] = "Shaman",
				["guild"] = "High Tide",
			},
			["Frostmist"] = {
				["name"] = "Frostmist",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Krocan"] = {
				["name"] = "Krocan",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Dandruk"] = {
				["name"] = "Dandruk",
				["class"] = "Hunter",
				["guild"] = "The Dark Brotherhood",
			},
			["Sgy"] = {
				["name"] = "Sgy",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Freezma"] = {
				["name"] = "Freezma",
				["class"] = "Mage",
				["guild"] = "SIN",
			},
			["Stabbeh"] = {
				["name"] = "Stabbeh",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Hurksmash"] = {
				["name"] = "Hurksmash",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Lustbliss"] = {
				["name"] = "Lustbliss",
				["class"] = "Priest",
				["guild"] = "SIN",
			},
			["Corrax"] = {
				["name"] = "Corrax",
				["class"] = "Shaman",
				["guild"] = "SIN",
			},
			["Rozaliina"] = {
				["name"] = "Rozaliina",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Chorum"] = {
				["name"] = "Chorum",
				["class"] = "Priest",
				["guild"] = "Cult",
			},
			["Haywanat"] = {
				["name"] = "Haywanat",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
			["Celembris"] = {
				["name"] = "Celembris",
				["class"] = "Shaman",
				["guild"] = "SIN",
			},
			["Vay"] = {
				["name"] = "Vay",
				["class"] = "Rogue",
				["guild"] = "SIN",
			},
			["Sustainlife"] = {
				["name"] = "Sustainlife",
				["class"] = "Hunter",
				["guild"] = "SIN",
			},
			["Bruteforge"] = {
				["name"] = "Bruteforge",
				["class"] = "Warrior",
				["guild"] = "SIN",
			},
		},
		["zone"] = "The Molten Core",
		["date"] = "2017-06-30 21:20:11",
		["reason"] = "The Molten Core: Golemagg the Incinerator",
		["foritem"] = "false",
		["points"] = 5,
		["awardedby"] = "Actar",
		["tableid"] = 1,
	},
}
WebDKP_DkpTable = {
	["Maage"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Drunkle"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Domogenitals"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Fafniel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Shantayah"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Boosbye"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Bigbeary"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Lookere"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Maner"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Shaguomashi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Undralat"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Amavi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Chunyemen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Cocles"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Pitaya"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Velzad"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Buick"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Millim"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Legallol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Secretlly"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Paulee"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Honge"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Xuaner"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Corrax"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Teri"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Cwarrior"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Xuyaoh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Helana"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Jambii"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Daawy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Okcokc"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Swiftdeus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Bovis"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Paleomgician"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Bigrenbeen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Fumanchuone"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Candycandy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Alexss"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Msexedead"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Samadhi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Selinameyer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Nones"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Avaell"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Oyr"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Pealr"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Hujumanji"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Unsw"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Xst"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Cevon"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Reyto"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Sciro"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Bmwo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Nexxm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Dianwei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Ichi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Chargex"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Idgaf"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Henks"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Iznogoud"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Wbw"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Beelzemut"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Ikuca"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Demetr"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Onesoul"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Shahidka"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Dahl"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Passens"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Somefeng"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Dontaskme"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Krocan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Joorl"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Mallie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Bobafat"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Beautifuldt"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Neverbetray"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Rendoran"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Dubaima"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Zrgn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Smorkniv"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Cki"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Quik"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Vodia"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Raikuli"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Blackmike"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Nazghrel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Zhangzhi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Warderer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Oneofus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Furminator"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Qqsha"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Watson"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Narazhak"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Scavia"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Happlahana"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Aktadig"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Blachgaard"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Lymetel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Amzo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Hiarmor"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Akton"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Gled"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Maggotbrain"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Moojjo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Ppapapplepen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Pepper"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Rotkoporsas"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Lukagos"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Amph"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Baida"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Auditor"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Kaway"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Ithanas"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Groa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Sodapoppiny"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Iwaskind"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Mokes"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Shueishuei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Haa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Aendos"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Maoti"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Apthook"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Kawf"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Ahtaaja"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Anewhand"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Gllaurung"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Xiaoxuanfen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Zereena"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Rhasha"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Darkeagle"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Schiffer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Noiro"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Fossegrimen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Wisewind"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Frankz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Mtguilai"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Targ"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Duroton"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Dethrone"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Pythagoraz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Zoups"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Fieldrations"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Valkary"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Lorbaz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Jaqenhghar"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Sgy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Jeanus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Kushlord"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Basswing"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Bluehorn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Dayfly"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Yaiks"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Shengxia"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Saybyebye"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Aziz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Miumiu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Ainominako"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Boon"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Morningstar"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Diavoly"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Tedeus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Rahilg"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Reay"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Atao"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Namz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Batulu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Liusu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Kh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Evool"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Deadlocke"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Moistcookie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Tumulten"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Mortaz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Xiongtao"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Hokote"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Exentouch"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Orcnstein"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Mallic"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Skulldragon"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Baragan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Himm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Noheaven"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Huangshi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Nofate"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Pvpsher"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Fuere"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Slurms"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Naihu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Enclaved"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Talunmier"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Kaelus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Backpferd"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Djdadslayerx"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Manapie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Thirteenye"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Unclebenn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Tituspullo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Verbero"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Stoffi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Imperishabil"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Kamaji"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Vict"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Eggen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Xband"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Daboba"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Bobob"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Wihte"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Shankys"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Xka"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Kshups"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Chenlin"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Valri"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Blueprophet"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Fulldot"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Bigbearjxl"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Vemesis"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Jackf"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Tomcruisey"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Avadakidabra"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Sustainlife"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Gnoramus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Everestlol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Qiangsheng"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Feep"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Zelsius"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Volience"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Luminescnece"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Tappotahti"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Proteinnerd"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Toast"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Qilandaa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Gurneyz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Huskin"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Duier"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Sinh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Momon"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Xiaofee"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Danklettuce"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Sommer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Celeanne"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Gravos"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Gundal"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Minni"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Acouphenes"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Jetr"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Senze"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Maligu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Casumarzu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Tessta"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Police"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Himarm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Anduvin"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Groun"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Kochen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Thegear"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Ntt"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Dabiantaism"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Onepixel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Applepears"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Chrisk"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Jisung"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Samael"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Skytravel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Heires"] = {
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Tygos"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Sscythe"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Dudro"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Bgk"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Chestnuts"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Xargon"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Bwm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Haozai"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Seawave"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Bonelless"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Haywanat"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Jiaoshouge"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Vadre"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Denominator"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Powerwordhug"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Hutouge"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Tomtrana"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Archt"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Antrila"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Panhu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Gove"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Actar"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Knw"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Zulisori"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Orkpocalypse"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Thaloss"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Chestnutz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Greezer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Orcst"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Mada"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Airbloodd"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Rakas"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Aein"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Ghouldone"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Kryne"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Zorrozero"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Uuo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Grookshank"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Shoaun"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Darkdance"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Ebowla"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Rals"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Starspace"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Noxxel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Agnoingas"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Muscleboy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Ranan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Hardess"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Zlight"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Ahrok"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Adidja"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Icelich"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Nomz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Iceicebabi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Ganoo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Sureo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Clydefrawg"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Ozaru"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Jonnyliz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Broxxigarr"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Zekratus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Chinahou"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Orkasm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Scarf"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Krypt"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Cryingsky"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Putaoii"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Laogui"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Darkconfes"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Orionnebula"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Naolejiupao"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Smek"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Asdren"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Forssa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Craned"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Zsgege"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Peredoz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Pocketpair"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Ragnok"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Caishen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Acatinthehat"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Congxin"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Kuluts"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Overbook"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Fengxixi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Kurtkuhbrain"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Haishen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Windmil"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Gallatrix"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Panamona"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Rozaliina"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Kuaikuai"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Busete"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Nth"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Trolla"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Mohicann"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Yihui"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Fugepone"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Zick"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Blindroger"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Magwynn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Silverzero"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Risivache"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Hikizuki"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Sykelol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Echolily"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Vesperia"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Reven"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["March"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Onlymortal"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Violencelee"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Chairmang"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Badtaste"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Pluton"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Ernik"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Rongye"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Barend"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Fiveye"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Bruteforge"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Blankya"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Icarax"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Laoshuzei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Panoramisk"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Pollypocket"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Minass"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Phaen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Wanglingmei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Maxsimus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Ext"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Whosee"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Dragonblood"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Qhl"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Snari"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Tatikoma"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Hexhellstorm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Eminas"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Vernak"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Yugoslavia"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Kublol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Tinging"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Forcebrg"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Raztaz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Papaya"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Insightt"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Moaki"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Sjq"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Bajacro"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Babysonfire"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Aoeff"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Evsen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Alvara"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Washburnn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Xiaorenyao"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Yamazak"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Memebean"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Nocannobibi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Octarinecore"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Nikanevaji"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Celembris"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Long"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Bobadillan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Ozzer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Canoptek"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Eddness"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Guozhi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Xiaoguangtou"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Exalteraw"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Seaport"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Maozong"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Kasha"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Dakk"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Chorum"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Pompalanecla"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Elany"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Idolpie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Bokthra"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Dsh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Proost"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Trashy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Tumar"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Stealhearts"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Crae"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Xixa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Jonkel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Tandzd"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Goforgruber"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Phoee"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Danders"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Neutronstar"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Lowshadow"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Zaijianni"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Nargi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Sml"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Vvispers"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Losira"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Poma"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Flawlezzlol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Preachermaam"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Diavola"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Yeyshen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Gralle"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Stemmhart"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Putridpile"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Daghost"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Archaius"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Everrett"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Sunriseboy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Acosta"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Hendidiao"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Illimatik"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Zytli"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Jutting"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Goingdown"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Mosn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Krishi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Kadoer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Xganjawizard"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Rekan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Zevaru"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Hezrul"] = {
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Diskk"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Ubime"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Mavrogatos"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Redlighht"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Zbtiandi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Oxietenf"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Hahaming"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Luckylulu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Makss"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Fans"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Cls"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Pastries"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Kahn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Enrica"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Acek"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Shiimti"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Stabbeh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Goldendream"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Stevedave"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Tabz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Voodoolab"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Apone"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Rivaille"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Chihewanle"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Molteny"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Grash"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Vlades"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Tbaggins"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Yjerry"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Hurksmash"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Smoughy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Killyy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Nagreil"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Lawxon"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Konm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Losttemp"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Gates"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Onokazu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Shanji"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Sotd"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Nicholastas"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Nicolasfour"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Fikou"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Madholy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Zoune"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Bananular"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Tauryn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Malagebi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Bluesvs"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Deathmask"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Malaz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Andhaka"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Ribokh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Fanwei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Qune"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Dragore"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Rellak"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Wischmob"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Gramrock"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Williamhungx"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Mdcox"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Niklaz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Konte"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Nalta"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Xiaoyangmei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Meanbaby"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Hien"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Supadupa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Houge"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Nightwar"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Punchme"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Mvy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Beeftraeger"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Ariklan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Unwanting"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Musicbox"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Haldir"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Kase"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Vagaga"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Jonhamstring"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Thrax"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Lustbliss"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Ziban"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Woshishaman"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Mukduck"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Morningdelay"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Therapist"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Iforgiveher"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Tolstoij"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Frostreaver"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Stumpy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Afresh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Nobreath"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Cheezeudders"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Voro"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Whitebull"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Philer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Fabricius"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Hyperborean"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Eisenhower"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Kissice"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Schnitzelman"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Miamu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Wootzz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Celibrave"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Oggep"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Menergy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Necio"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Baarbara"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Naxxwaswotlk"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Elalabama"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Skogs"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Oopss"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Lemonlock"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Crashlanding"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Matchme"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Hayatpwn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Danadan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Fangniuwa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Tianxun"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Ripatcore"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Phatmage"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Darthsidius"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Faves"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Poxer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Grugan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Meowmm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Chapsterz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Oozaru"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Droodsie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Stickyickey"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Drenched"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Justdie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Zeezuu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Coorsbanquet"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Saylove"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Littlepig"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Xiaosini"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Krad"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Frostmist"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Spellock"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Ocapa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Millennion"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Slobodanovic"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Razzarzor"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Lysh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Zairo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Aliencowfrog"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Kallemerax"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Seedie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Huitouwuan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Wharepaku"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Iizipiizi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Laodage"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Xiaoshuikeng"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Fasii"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Raorkan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Littlegeorge"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Vesca"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Durzub"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Ryaba"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Zluth"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Caiblol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Sofiabhe"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Tyrfing"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Creepie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Underworld"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Wuzzy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Warthunder"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Varycia"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Skywolker"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Fireok"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Zugo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Windowsil"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Capratax"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Xorvus"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Rosely"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Kensaku"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Rephaim"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Pencel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Babadook"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Cheaptrickz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Guerilla"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Xart"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Zupr"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Lzz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Caxide"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Xinzei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Bujusima"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Firematch"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Rabbitbaby"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Mebouls"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Volatility"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Katsuto"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Pandoraii"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Jecc"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Roze"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Pheal"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Lothario"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Hextall"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Yumcha"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Galtarak"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Azmage"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Xieshendashu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Seldox"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Mafengwo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Swixt"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Nawa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Idotalot"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Klox"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Jeatio"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Tankerguy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Spherica"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Xionm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Zahnfee"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Fayten"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Finafir"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Ekstrey"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Xeetwo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Ule"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Ayada"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Totoo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Honsol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Korando"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Mawl"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Backo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Altzheimer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Jiajun"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Phaed"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Hornstorm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Slotty"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Luckydog"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Flameboy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Piziheroes"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Labadze"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Priest",
	},
	["Sgamer"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Loveitbehind"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Grimn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Thender"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Vittorino"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Vez"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Kotol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Cutemeatball"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Rahmbro"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Bollis"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Psykbryt"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Methke"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Hente"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Unknown"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Druid",
	},
	["Breze"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Maybenextime"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Jjk"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Pinzel"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Hellogirls"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Electraheart"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Withthewrist"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Cexi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Thrill"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Shaman",
	},
	["Weave"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Uhf"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Huntat"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Pakalolo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Jeo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Freezma"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Greytrack"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Chasseurr"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Noelife"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Missvivian"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Xiongzhong"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Justicecream"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Sran"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Vay"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Sneakyhobo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Dandruk"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Mubiao"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Viy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Blumedy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Mathos"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Gulyawn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Deathknell"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Stenolom"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Shelia"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Aihai"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Taake"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Rykhh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Legulas"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Nozx"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Eajle"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Nahts"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Tuvalu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Letmetankpls"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Prle"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Fvan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Endlessl"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Trupoedov"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Sanger"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Wanggelol"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Gordec"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Ironwoman"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Chillmurray"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Ferzb"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Insist"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Mianbao"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Kons"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Warwings"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Dalola"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Teochew"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Lourens"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Wiseguyhuh"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Hunter",
	},
	["Duzyizly"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Ooliee"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Xdzei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Zayle"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Rofldots"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Yxl"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Massiverage"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Cannawizard"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Elgincq"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Ilililililii"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Jdoe"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Powar"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Ampzor"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Xueyufei"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warrior",
	},
	["Folgore"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Bovvan"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Soloshow"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Lil"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Shishi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Kontaz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 15,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Dagdamor"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Mojingwa"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Druid",
		["Selected"] = false,
	},
	["Fatnfly"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Mianmen"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Mage",
		["Selected"] = false,
	},
	["Funkyworkz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Pseu"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Delrobero"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Msolo"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Aiaii"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Priest",
		["Selected"] = false,
	},
	["Nigell"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warlock",
		["Selected"] = false,
	},
	["Sdwind"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Rogue",
	},
	["Fraerock"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
	["Bedlieve"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Rogue",
		["Selected"] = false,
	},
	["Titanigor"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Shaman",
		["Selected"] = false,
	},
	["Jwm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Warlock",
	},
	["Schwammerl"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Warrior",
		["Selected"] = false,
	},
	["Socro"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "Mage",
	},
	["Alexess"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "Hunter",
		["Selected"] = false,
	},
}
WebDKP_Tables = {
}
WebDKP_Loot = nil
WebDKP_WebOptions = {
	["ZeroSumEnabled"] = 0,
}
WebDKP_BenchList = {
}
WebDKP_Bench_TotalToday = 10
